# Welcome to Jekyll!

# Website settings
title: Shin's Portfolio
description: Jack's blog,use Jekyll and github pages.
keywords: blog,Jekyll,github,gh-pages
baseurl:  # if you have suburl as homepage like '/homepage', please change it to '/homepage' and your repo's name should be 'homepage'
url: https://jarrekk.github.io/Jalpc  # url should be 'http://<github_username>.github.io/homepage' as before
# url: http://127.0.0.1:4000
img_path: /ShinSeraPortfolio/static/assets/img/blog  # url should be '/homepage/static/assets/img/blog' as before

# author -- index page "about me" section
author:  # change following line to your infomation.
  name: Shin Yeoeun  # Be used at blog posts' author.
  first_name: SHIN  # Be used at index page about me section.
  last_name: YEOEUN  # Be used at index page about me section.
  avatar: /static/assets/img/landing/avatar.jpg  # upload your avatar at directory and edit it.
  github_username: shinyeoeun  # Leave blank if you don't have now
  linkedin_id: shin-yeoeun-97255214a # Leave blank if you don't have now
  facebook_username: yeoeun.shin  # Leave blank if you don't have now
  email: shinyeoeun@gmail.com  # Leave blank if you don't have now
  skill_icon1:
    - name: icon-apache
    - name: fa-linux
  skill_icon2:
    - name: fa-linux
    - name: icon-apache
  desc: SW 테스트 엔지니어</br>3년간 개발자로서 SI프로젝트를 진행하다, SW테스트엔지니어로 전향하여 테스트＆테스트자동화업무를 진행하고 있습니다.</br>애자일 개발 환경에서의 테스트 자동화에 관심이 있으며 테스트 자동화가 소프트웨어 품질 향상에 기여할 것이라고 믿고있습니다.

# analytics
## google analytics
ga:  # if you wanna this feature, go to https://www.google.com/analytics/ to get your configuration; if not, comment following line.
  #id: UA-93473370-3

## google optimize
go:
  # id:

## carousels
index_carousel: on  # index page carousel switch
blog_carousel: on  # blog page carousel switch

# scss
sass:
  style: compressed

# Build settings
encoding: utf-8

# other settings
highlighter: rouge
markdown: kramdown
kramdown:
  input: GFM
  syntax_highlighter: rouge
